---
title: "Untitled"
author: "Jacob Haywood"
date: "3/11/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r}
monty_hall_one_play <- function(){
    
  
  all <- c(1,2,3)
  actual <- sample(all,1)
  choice <- sample(all,1)
  host <- subset(all,all != actual)
  host <- subset(host,host != choice)
  host <- sample(host,1)
  end <- c(actual,choice,host)
  
  return (end)

}
```


```{r}
monty_hall_one_play()

monty_hall <- function(iter){
  df <- data.frame()
  for (i in seq(1:iter)){
  arr <- monty_hall_one_play()
  if (arr[2] != arr[1]){
    switch_win <- 1
    stay_win <- 0
  }
  else {
    stay_win <- 1
    switch_win <- 0
  }
  df <- rbind(df,c(arr[2],arr[1],arr[3],switch_win,stay_win))
  }
  return(df)
}
```

```{r}
mh_10000 <- monty_hall(10000)
names(mh_10000) <- c("car_door","initial_choice","door_reveal","switch_win","stay_win")
sapply(mh_10000,mean)
```

The best strategy is to switch.
Yes, the simulated win probabilities are close to 1/3 for stay and 2/3 for switch

```{r}
arr1 <- c()
arr2 <- c()
for (i in seq(1:10000)){
  x <- mean(mh_10000$switch_win[1:i])
  y <- mean(mh_10000$stay_win[1:i])
  arr1[i] <- x
  arr2[i] <- y
  
}

plot(c(1:10000),arr1,'l')
```

```{r}
plot(c(1:10000),arr2,'l')
```

